document.getElementsByTagName("td")[0].innerHTML = "Tuomas";
document.getElementsByTagName("td")[1].innerHTML = "Myllyoja";
document.getElementsByTagName("td")[2].innerHTML = "Sumppiz";
document.getElementsByTagName("td")[3].innerHTML = "Ruukinlahdentie 3 A 15, 00200, Helsinki";
const tr1 = document.querySelector("#1");
const th1 = document.createElement("th");
const t1 = document.createTextNode("Puh.");
th1.appendChild(t1);
tr1.appendChild(th1);
const tr2 = document.querySelector("#2");
const td2 = document.createElement("td");
const t2 = document.createTextNode("0405308204");
td2.appendChild(t2);
tr2.appendChild(td2);
document.getElementsByTagName("th")[2].innerHTML = "";
document.getElementsByTagName("td")[2].innerHTML = "";
